### ISSUE TITLE
Support DPMS as alternative to DDC/CI

### ISSUE THREAD

**Issue by tdryer** [haimgel/display-switch#38]
My display doesn't accept DDC/CI requests from inactive inputs:

```sh
$ # Input is active:
$ ddcutil --bus=7 getvcp 60
VCP code 0x60 (Input Source                  ): DVI-1 (sl=0x03)

$ # input is inactive:
$ ddcutil --bus=7 getvcp 60
DDC communication failed for monitor on I2C bus /dev/i2c-7
```

This means that display-switch can change to a different input, but it can't change back.

I found [a reference](https://github.com/rockowitz/ddcutil/issues/83#issuecomment-627655363) suggesting that this could be a common limitation.

I wrote [a script](https://github.com/tdryer/usb-display-switch/blob/master/usb-display-switch) that instead uses [DPMS](https://en.wikipedia.org/wiki/VESA_Display_Power_Management_Signaling) to control display standby. If a system on one input enables standby, and another disables it, the display switches to the only active input.

display-switch could implement this DPMS approach to support monitors that limit DDC/CI to active inputs.

**Comment by haimgel** [comment]
Interesting. I think that even if your monitor does not support DDC/CI from inactive inputs, the app could still work for you if you configure just the `on_usb_disconnect` settings on both computers. `on_usb_connect` cannot be used because you're trying to control from the inactive input, but "on disconnect" should work, correct?

**Comment by tdryer** [comment]
You're right, using `on_usb_disconnect` works.
