### ISSUE TITLE
windows 10, app refuses to start

### ISSUE THREAD

**Issue by kurktchiev** [haimgel/display-switch#82]
on first run i got the SmartScreen popup asking me if i was sure, which i said I was. I put my ini file in the correct location and started the binary, but nothing comes up in Task Manager. Put it in the startup folder and rebooted for good measure, it is still not starting and no log file is being generated.

**Comment by jrr** [comment]
Have you tried running it from a command prompt?

**Comment by kurktchiev** [comment]
That I have not yet

**Comment by stevegore** [comment]
FWIW I have it running by adding it to a Windows batch file, and adding that batch file to the start up folder. Have yet managed to get it to start minimised though so it's not the best.

**Comment by LegendaryB** [comment]
> FWIW I have it running by adding it to a Windows batch file, and adding that batch file to the start up folder. Have yet managed to get it to start minimised though so it's not the best.

My solution was a launcher.bat + a helper vbs script. Here you go:

hidecmd.vbs
`CreateObject("Wscript.Shell").Run """" & WScript.Arguments(0) & """", 0, False`

launcher.bat
`wscript "hidecmd.vbs" "display_switch.exe"`

I decided to execute the launcher.bat via registry instead of adding it to the startup folder. At startup the cmd window can be seen for a short time but afterwards its hidden. Maybe 1 second visible
